# Quickstart: Black Duck Security Scan Action with polaris:
#     https://documentation.blackduck.com/bundle/bridge/page/documentation/t_github-polaris-quickstart.html
name: Polaris Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Polaris Security Scan
        id: polaris-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          ### ASSESSMENT TYPES
          polaris_assessment_types: SAST,SCA  # Comma-separated list: SAST,SCA,DAST
          ### Mark build status if policy violating issues are found
          mark_build_status: success  # Set to success, failure, or skip
